language: ruby

cache:
  bundler: true
  directories:
    - 'spec/fixtures/puppet_controlrepo/.onceover' # Onceover cache

script: bundle exec rake full_tests
bundler_args: --path vendor/bundle

rvm:
  - 2.3.8
  - 2.4.4
  - 2.5.3
