language: ruby

cache:
  bundler: true
  directories:
    - 'spec/fixtures/puppet_controlrepo/.onceover' # Onceover cache

script: bundle exec rake full_tests
bundler_args: --path vendor/bundle

rvm:
  - 2.1.6
  - 2.1.7
  - 2.1.8
  - 2.1.9
  - 2.2.7
  - 2.3.4
  - 2.4.0
  - 2.4.1
  - 2.4.2
